# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NinMapper
                                 A QGIS plugin
 Natur i Norge (NiN) mapping tool.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-03
        copyright            : (C) 2024 by Lasse Keetz, Peter Horvath
        email                : test@dev.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NinMapper class from file NinMapper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .nin_qgis_plugin import NinMapper
    return NinMapper(iface)
